# Generated by Django 3.2 on 2021-04-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210411_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_İmage',
            new_name='article_image',
        ),
    ]
